apiVersion: v1
kind: Service
metadata:
  name: webapp-backend-service
  namespace: webapp-backend
  labels:
    app: webapp-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: webapp-backend
